import type { Metadata } from "next";
import Link from "next/link";
import { Header, Footer } from "@/components/chrome";

export const metadata: Metadata = { title: "Privacy & your words", description: "How this showcase website works, and a plain-language overview of privacy choices inside Lantern Post." };

export default function PrivacyPage() {
  return <><Header /><main id="main-content" className="container privacy-page"><p className="eyebrow">A LITTLE CLARITY, WITH CARE</p><h1>Privacy &amp;<br /><em>your words.</em></h1><p className="privacy-lead">This page explains the showcase and the app&apos;s main privacy choices. The full app policies are available inside Lantern Post.</p><div className="guide-prose"><section><h2>This showcase website</h2><p>You do not need an account to explore this website. Its sample letters, stationery choices, and companion previews run in your browser. They do not create a Lantern Post account, deliver a letter, record your voice, or connect Google Drive.</p><p>We have not added analytics, advertising trackers, contact forms, or a connection to the app&apos;s private API. Your preview choices are kept in the current page&apos;s memory and reset on a fresh visit. The host, Vercel, may process ordinary connection and request information to serve and secure the website.</p><p>The download link opens GitHub. GitHub handles that request and download under its own policies. No APK is uploaded from your phone to this website.</p></section><section><h2>Inside Lantern Post</h2><p>Unsent drafts and voice recordings stay on the device until you explicitly share, deliver, publish, or back up eligible content. A shared Infinity letter is visible to signed-in community members. A private letter is delivered to an accepted friend. Signing is a choice; being unsigned does not hide the author from the service.</p><p>Ordinary letters and chat are not described as end-to-end encrypted. Optional backup archives are encrypted, and their recovery keys stay with you. Removing an ordinary private letter removes your own copy; full account removal is a separate confirmed process.</p><p>Authentication, hosting, delivery storage, notifications, and optional Google Drive connections use their respective services. Review the full in-app policies for the current handling of account data, content, reports, retention, and external cleanup. Those app policy drafts still require the operator&apos;s final legal/contact details.</p></section><section><h2>Your choices</h2><p>Use the app&apos;s controls to choose a destination, manage drafts, turn off arrival popups or diagnostics, pause motion, disconnect Drive, block/report, and request account removal. Microphone and phone-notification access are managed with your device&apos;s permission controls.</p><p>Lantern Post is for users aged 13 or older, subject to higher local age requirements. Automated content moderation is not active in this release, and reporting does not promise an immediate response.</p><Link className="text-link" href="/guide#your-controls">Read about the app controls →</Link></section></div></main><Footer /></>;
}
