export const policyEdition = '14 September 2026 · development review draft';
export const publisherName = 'The Lantern Post';
export const minimumAge = 13;
export const policyReviewNotice = 'These policies describe the current development product. The publisher’s legal details, country, public contact and launch terms must be completed before a public release.';
export type PolicyKind = 'terms' | 'privacy';
export const policies: Record<PolicyKind, { title: string; sections: { title: string; text: string }[] }> = {
  terms: { title: 'Terms of Service', sections: [
    { title: 'Welcome to The Lantern Post', text: 'The Lantern Post offers a personal writing space, voice letters, private friend delivery and a shared Infinity World. The current product is in development; delivery depends on the services available in your build. These review terms are not a claim that a public launch has taken place.' },
    { title: 'Who may use the palace', text: 'You must be at least 13 years old, and meet any higher minimum age required where you live. If local law requires a parent or guardian’s permission, obtain it before using the service. Do not create accounts for children below the applicable minimum age. Age confirmation does not ask you to provide a full date of birth.' },
    { title: 'Your account and your words', text: 'Keep your sign-in secure and use an account you are entitled to access. You retain rights in your words and recordings. By choosing a delivery destination, you permit the service to process, store and show that letter as needed for that destination and to apply safety controls. Do not submit material you lack permission to share.' },
    { title: 'Choosing who can read', text: 'Local drafts stay on the current device until you choose to share or send. Sealing alone does not send. Private delivery is to an accepted friend. Infinity World letters are visible to eligible signed-in community members and are unsigned unless you explicitly sign with your username. An unsigned letter is not anonymous to the service. Share a copy exports to an app you choose; recipients of that copy may save or forward it outside our controls.' },
    { title: 'Keep the world kind', text: 'Do not use the service for threats, harassment, hate, exploitation, sexual content involving minors, unlawful activity, spam, impersonation or sharing someone else’s private information without permission. Automated content moderation is not active in this version. Confirmed chat messages and friend/public letters can be delivered without an automated content check. Journey previews do not deliver letters. Do not attempt to evade blocks, request limits or account protections.' },
    { title: 'Reports, blocks and availability', text: 'You can report eligible received letters and close gates to other accounts. Reports are saved for review; the app does not promise a live response. Blocking ends friendship, and unblocking does not restore it. A public release may restrict or remove content or accounts to address violations, legal requirements or security problems. Support resources are informational and are not emergency or medical care.' },
    { title: 'Release, copies and local storage', text: 'Confirming a burn permanently clears the local letter after its release is confirmed. It cannot retract copies you previously exported or shared. Device storage can be lost if you clear browser data, uninstall the app or lose the device. Completed journeys retain content-free receipts for recovery and limits. Read the Privacy Policy for the current retention behaviour.' },
    { title: 'Collections and release details', text: 'All currently active companions and stationery, including the Royal Collection, are free. No subscription or purchase is active. Changes to pricing or material terms would need separate notice and any required agreement. The operator’s legal identity, contact, governing-law provisions, service commitments and dispute terms remain to be finalized for launch; mandatory local rights are not waived by this draft.' },
  ] },
  privacy: { title: 'Privacy Policy', sections: [
    { title: 'Friendship conversations', text: 'Real-time text chat is restricted to currently accepted, unblocked friends. Confirmed messages are stored on the server after friendship, block and account checks. Automated content checks are disabled in this version. Unsent words and already-confirmed pending requests are kept separately for each account and friend on the device; confirmed delivery clears that local draft. Conversation history remains on the server, and blocking removes access without automatically deleting the transcript. Reports and content-free delivery/cancellation receipts are retained for safety and reliable retries. A sample parlour makes no send request and does not change the real draft. Confirmed account removal clears readable conversations involving that account, while limited content-free receipts and report records remain. Final retention periods still need operator review.' },
    { title: 'Who operates the service', text: 'The product’s publisher name is The Lantern Post. This development policy is a review draft. The legal operator, operating country and public privacy/support contact have not yet been supplied and must be added before public release.' },
    { title: 'Account and device information', text: 'Clerk handles authentication, including your email or chosen sign-in provider. The app stores an account reference, username, companion choice, age confirmation and preferences. Friendship requests, blocks, reports and request budgets support the social and safety features. Prepared phone notification features may register a device token when enabled; live native push setup is currently deferred.' },
    { title: 'Drafts and voice recordings', text: 'Written drafts, stationery choices and pending operation records are saved separately for each account on the device. Browser voice bytes are held in IndexedDB; phone voice bytes use app document storage. Microphone access is requested when you start recording, with a three-minute limit and no autoplay. An optional written version is stored with the voice letter. This local separation is not end-to-end encryption and does not protect a shared browser profile from someone with device access.' },
    { title: 'When content leaves your device', text: 'A confirmed friend or public send submits words, or uploads recording bytes and an optional written caption to configured storage, for delivery. Automated text and voice moderation is disabled. Recordings are checked for valid format, size, duration and upload ownership before delivery. Burning does not upload audio or its caption; written burning content is processed for the release request and is not retained as letter content. Preview journeys make no send or upload. Share a copy creates a file or written copy only when you ask; the chosen outside app’s own privacy policy then applies.' },
    { title: 'Voice storage and optional backups', text: 'Voice drafts are stored on your device. Sending a voice letter uploads a private delivery copy so its recipient can listen while you are offline; the current free-storage integration uses Supabase when configured. You can separately create an encrypted backup of your own unfinished voice recording on this device or in your connected Google Drive account. Including its written caption is optional. You must keep the recovery key separately; it is not uploaded and cannot be recovered by us. After reinstalling, sign in to the original account and open the backup with its key to listen or save the recording. Backup copies do not send letters or automatically restore pending deliveries. Local data can be lost when the app or browser storage is cleared.' },
    { title: 'Removing your copy of a private letter', text: 'Removing a private letter hides it from your own letterbox. The other participant keeps their copy. Shared text, captions and recording bytes are cleared when both participants remove the letter, subject to cleanup retries and retained content-free receipts. Removing an entire account is a separate confirmed process that clears its shared content; public-letter removal also remains separate.' },
    { title: 'Arrival alerts', text: 'The app uses short-lived, account-private arrival metadata to refresh friendship gates, letters and conversations. In-app alerts can be turned off. Prepared phone notifications use generic text and routing identifiers rather than message or letter contents. Phone alerts require an installed app, permission and configured delivery services.' },
    { title: 'Who sees a delivered letter', text: 'A private letter is available to its intended recipient while friendship and block rules permit. Delivered Infinity World letters can be opened by eligible community members. Signing reveals only the chosen username publicly. Unsigned public responses omit your account ID and companion; the server still knows the author for ownership, reporting and blocking. Letter lists do not include voice captions. Public IDs and anonymous blocking aliases are separate from recovery receipts.' },
    { title: 'Retention and deletion', text: 'Unfinished local letters remain on the device until you remove the draft in My letters, replace its contents, release/send it or clear that device’s app data. Removing a draft clears its words, caption and recording descriptor, queues any local audio for deletion, and keeps a small content-free marker so an older window cannot restore the page. You may also remove a recording while keeping its draft. After confirmed delivery or burn, local content is cleared and any recording deletion is durably queued. Delivered content stays on the server until removed under the applicable controls. Removed content is cleared; due deletion work runs in bounded background sweeps and recording objects are queued for cleanup, so outages may delay physical removal. Cleared, unreported audit stubs older than 30 days can be purged. Reported audit stubs, reports, operational receipts and limit records are retained as required for safety and reliable operation; this build does not set a final time limit for all of those records.' },
    { title: 'Optional diagnostics', text: 'Basic diagnostics are off by default. If enabled, the app records a restricted set of event names, platform, event identifiers, applicable operation identifiers and fixed error codes with a random key tied to that consent. It excludes letter and voice content, captions, usernames, raw errors, stacks and support-suggestion matches. Events expire after 30 days. Opting out clears stored diagnostic events and resets the consent key. Optional configured Sentry forwarding contains fixed error codes, platform and release only; already exported events cannot be recalled automatically.' },
    { title: 'Providers, choices and young people', text: 'Authentication, hosting, database, storage and any later configured moderation, push or diagnostics services process information needed for their functions. The production provider list, hosting regions, transfer safeguards, backup retention and request-handling process must be finalized before launch. Use account controls for diagnostics, microphone settings for recording, and available letter/block/report controls for content. The minimum age is 13 or a higher local requirement. A public contact for access, correction, deletion and age-related requests is still required before release. Account removal includes local cleanup and a background retry process for connected providers. Exported copies and files on other devices cannot be recalled. No live support response is promised by this development draft.' },
  ] },
};
