import { useState } from 'react';
import { Image, Pressable, StyleSheet, Text, useWindowDimensions, View } from 'react-native';
import { Flourish, StoryIcon } from '../storybook/ornaments';
import { RoyalNavButton } from '../storybook/royal-navigation';
import { serif } from '../storybook/theme';
const artwork = { infinity: require('../../assets/storybook/destination-infinity.png'), friend: require('../../assets/storybook/destination-friend.png'), fire: require('../../assets/storybook/destination-fire.png') };
export function DestinationCourt({ onWorld, onFriend, onBurn, onBack, onUnseal, disabled }: { onWorld?: () => void; onFriend?: () => void; onBurn?: () => void; onBack: () => void; onUnseal: () => void; disabled: boolean }) {
  const { width } = useWindowDimensions();
  return <View testID="royal-destination-court" style={[styles.court, width < 600 && { padding: 14, gap: 16 }]}><View style={[styles.inset, { pointerEvents: "none" }]} /><View style={styles.heading}><Flourish width={148} /><Text style={styles.eyebrow}>THREE PATHS THROUGH THE PALACE</Text><Text role="heading" style={[styles.title, width < 600 && { fontSize: 26 }]}>The royal post awaits.</Text><Text style={styles.subtitle}>A shared sky, a familiar gate, or the quiet of the fire. Choose the path that feels right.</Text></View>
    <View style={[styles.paths, width < 780 && { flexDirection: 'column' }]}>
      {onWorld && <Portal kind="infinity" title="The Infinity World" line="Let your words become a little light among the stars." label="Send to the Infinity World" number="I" onPress={onWorld} disabled={disabled} />}
      {onFriend && <Portal kind="friend" title="A friend’s palace" line="Carry your sealed letter to a familiar soul beyond the roses." label="Send to a friend's gate" number="II" onPress={onFriend} disabled={disabled} />}
      {onBurn && <Portal kind="fire" title="The Everflame" line="Let the fire hold what you are ready to release." label="Let it go to the fire" number="III" onPress={onBurn} disabled={disabled} />}
    </View><Text style={styles.note}>Your letter stays with you until you confirm its journey.</Text><View style={styles.rest}><RoyalNavButton label="Open my letter again" icon="letter" onPress={onUnseal} /><RoyalNavButton label="Return to my palace" icon="gate" onPress={onBack} /></View>
  </View>;
}
function Portal({ kind, title, line, label, number, onPress, disabled }: { kind: keyof typeof artwork; title: string; line: string; label: string; number: string; onPress: () => void; disabled: boolean }) {
  const [lit, setLit] = useState(false);
  const { width } = useWindowDimensions(); const small = width < 600;
  return <Pressable accessibilityRole="button" accessibilityLabel={label} accessibilityState={{ disabled }} aria-disabled={disabled} disabled={disabled} onPress={onPress} onHoverIn={() => setLit(true)} onHoverOut={() => setLit(false)} onFocus={() => setLit(true)} onBlur={() => setLit(false)} style={({ pressed }) => [styles.portal, small && mobile.portal, (lit || pressed) && styles.lit, disabled && { opacity: .5 }]}>
    {!small && <View style={[styles.portalInset, { pointerEvents: "none" }]} />}<Image source={artwork[kind]} style={small ? mobile.art : styles.art} resizeMode={small ? 'contain' : 'cover'} accessible={false} /><View style={[styles.words, small && mobile.words]}>{!small && <Text style={styles.ordinal}>PATH {number}</Text>}<Text style={[styles.portalTitle, small && { fontSize: 18, textAlign: 'left' }]}>{title}</Text><Text style={[styles.portalCopy, small && { textAlign: 'left', minHeight: 0 }]}>{line}</Text><View style={[styles.choose, small && { minHeight: 24, paddingTop: 4 }]}><Text style={[styles.chooseText, small && { fontSize: 13 }]}>Choose this path</Text><StoryIcon kind="arrow" size={16} color="#8A6934" /></View></View>
  </Pressable>;
}
const mobile = StyleSheet.create({
  portal: { flex: undefined, flexDirection: 'row', alignItems: 'center', borderTopLeftRadius: 6, borderTopRightRadius: 6, borderBottomLeftRadius: 6, borderBottomRightRadius: 6, boxShadow: 'none', paddingLeft: 8 },
  art: { width: 64, height: 88, flexShrink: 0 },
  words: { flex: 1, minWidth: 0, alignItems: 'flex-start', padding: 12, gap: 7 },
});
const styles = StyleSheet.create({ court: { width: '100%', maxWidth: 1120, padding: 24, marginTop: 16, backgroundColor: '#EDE1C7', borderColor: '#AE8D52', borderWidth: 1, borderTopLeftRadius: 38, borderTopRightRadius: 38, borderBottomLeftRadius: 6, borderBottomRightRadius: 6, gap: 22 }, inset: { ...StyleSheet.absoluteFill, margin: 6, borderWidth: 1, borderColor: '#CDB684', borderTopLeftRadius: 32, borderTopRightRadius: 32, borderBottomLeftRadius: 3, borderBottomRightRadius: 3 }, heading: { alignItems: 'center', gap: 12, paddingTop: 8 }, eyebrow: { color: '#8B7041', fontSize: 8, letterSpacing: 2, textAlign: 'center' }, title: { color: '#594129', fontSize: 32, fontFamily: serif, textAlign: 'center' }, subtitle: { color: '#816D4B', fontFamily: serif, fontStyle: 'italic', fontSize: 15, lineHeight: 23, maxWidth: 540, textAlign: 'center' }, paths: { flexDirection: 'row', gap: 18 }, portal: { flex: 1, minWidth: 0, backgroundColor: '#FAF0D9', borderColor: '#BA9C62', borderWidth: 1, borderTopLeftRadius: 90, borderTopRightRadius: 90, borderBottomLeftRadius: 5, borderBottomRightRadius: 5, overflow: 'hidden', boxShadow: '0px 5px 0px rgba(119,88,40,.12)' }, portalInset: { ...StyleSheet.absoluteFill, zIndex: 1, borderWidth: 1, borderColor: '#D7BE8A', margin: 5, borderTopLeftRadius: 85, borderTopRightRadius: 85, borderBottomLeftRadius: 2, borderBottomRightRadius: 2 }, art: { width: '100%', aspectRatio: 320 / 240 }, words: { alignItems: 'center', padding: 19, gap: 12 }, ordinal: { color: '#997B47', fontSize: 8, letterSpacing: 2 }, portalTitle: { color: '#60462B', fontFamily: serif, fontSize: 24, textAlign: 'center' }, portalCopy: { color: '#7A674B', fontSize: 12, lineHeight: 21, textAlign: 'center', minHeight: 44 }, choose: { minHeight: 44, flexDirection: 'row', alignItems: 'center', gap: 10, borderTopWidth: 1, borderColor: '#DBC493', paddingTop: 10 }, chooseText: { fontFamily: serif, fontSize: 16, color: '#805F2D' }, note: { color: '#7B6747', fontSize: 11, lineHeight: 19, textAlign: 'center' }, rest: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'center', gap: 15 }, lit: { borderColor: '#8C6B32', backgroundColor: '#FFF6DF', boxShadow: '0px 4px 14px rgba(140,107,50,.23)', outlineColor: '#A78644', outlineWidth: 2, outlineStyle: 'solid' } });
