import type { PalaceEventKind,PalaceEventPage,PalaceLiveEvent } from '@lantern-post/shared-types';
const kinds:PalaceEventKind[]=['FRIENDS_CHANGED','FRIEND_REQUEST','FRIEND_ACCEPTED','LETTERBOX_CHANGED','LETTER_REMOVED','LETTER_RECEIVED','CHAT_CHANGED','CHAT_RECEIVED','GATES_CHANGED'];
export function readPalaceEvents(input:unknown):PalaceEventPage {
  if(!input||typeof input!=='object')throw Error('Invalid live update.');const p=input as PalaceEventPage;
  if(!Array.isArray(p.events)||p.events.length>50||!Number.isSafeInteger(p.cursor)||p.cursor<0||typeof p.reset!=='boolean')throw Error('Invalid live page.');
  let previous=0;const events=p.events.map(e=>{if(!e||typeof e.id!=='string'||e.id.length<1||e.id.length>180||!Number.isSafeInteger(e.sequence)||e.sequence<=previous||e.sequence>p.cursor||!kinds.includes(e.kind)||typeof e.alert!=='boolean'||(e.seen!==undefined&&typeof e.seen!=='boolean')||typeof e.createdAt!=='string'||!Number.isFinite(Date.parse(e.createdAt))||e.peerId!==null&&(typeof e.peerId!=='string'||!/^[a-zA-Z0-9_-]{1,100}$/.test(e.peerId))||e.itemId!==null&&(typeof e.itemId!=='string'||!/^[a-zA-Z0-9_:-]{1,180}$/.test(e.itemId)))throw Error('Invalid live event.');previous=e.sequence;return {id:e.id,sequence:e.sequence,kind:e.kind,peerId:e.peerId,itemId:e.itemId,createdAt:e.createdAt,alert:e.alert,...(e.seen===undefined?{}:{seen:e.seen})};});
  return {events,cursor:p.cursor,reset:p.reset};
}
export function arrivalCopy(event:PalaceLiveEvent){switch(event.kind){case 'CHAT_RECEIVED':return {title:'A whisper at your gate',body:'A friend has sent a new message.',action:'Open the parlour'};case 'LETTER_RECEIVED':return {title:'A letter has arrived',body:'A sealed envelope is waiting in your letterbox.',action:'Open my letterbox'};case 'FRIEND_REQUEST':return {title:'An invitation awaits',body:'Someone has left an invitation at your palace gate.',action:'Open the court'};default:return {title:'A friendship gate has opened',body:'Your invitation has been accepted.',action:'Open the court'};}}
export type PalaceDestination={screen:'friends'|'inbox'}|{screen:'chat';peerId:string};
export function eventDestination(event:PalaceLiveEvent):PalaceDestination {return event.kind==='CHAT_RECEIVED'&&event.peerId?{screen:'chat',peerId:event.peerId}:event.kind==='LETTER_RECEIVED'?{screen:'inbox'}:{screen:'friends'};}
