import { VoiceBackupPicker,VoiceBackupReader } from './voice-backup-controls';
import { prepareVoiceBackup,openVoiceBackup } from './voice-backup';
import type { VoiceArchive } from './voice-backup-contract';
import { draftStorage } from '../letters/draft-storage';
import { useCallback,useEffect,useRef,useState } from 'react';
import { AppState,Text,TextInput,View } from 'react-native';
import { randomUUID } from 'expo-crypto';
import type { GetSessionToken } from '../api/client';
import { ApiError,apiRequest } from '../api/client';
import { StoryButton,StoryDialog,StoryHeading,s } from '../storybook/story-ui';
import { WaxSeal } from '../letters/stationery';
import { backupStore } from './backup-storage';
import { collectArchive } from './backup-api';
import type { BackupManifest } from './backup-api';
import type { BackupArchive,EncryptedBackup } from './backup-contract';
import { decryptArchive,encryptArchive } from './backup-crypto';
import { exportBackup,importBackup,prepareDriveWindow } from './backup-files';
import { assertAccountOpen } from '../account/account-fence';
const panel={borderWidth:1,borderColor:'#B99A61',borderRadius:24,padding:24,gap:18,backgroundColor:'#F3E8CF'} as const;
export function BackupRoom({ownerId,getToken}:{ownerId:string;getToken:GetSessionToken}) {
  const [local,setLocal]=useState<{id:string;createdAt:string}[]>([]);const [drive,setDrive]=useState<{id:string;createdAt:string}[]>([]);const [status,setStatus]=useState({configured:false,connected:false});const [busy,setBusy]=useState(false);const [notice,setNotice]=useState('');
  const [prepared,setPrepared]=useState<{envelope:EncryptedBackup;recoveryKey:string;target:'local'|'drive';source?:{key:string;revision:string|null}}|null>(null);const [unlock,setUnlock]=useState<EncryptedBackup|null>(null);const [key,setKey]=useState('');const [archive,setArchive]=useState<BackupArchive|null>(null);const [voiceArchive,setVoiceArchive]=useState<VoiceArchive|null>(null);const [shown,setShown]=useState(50);const [thread,setThread]=useState(0);const [remove,setRemove]=useState<{id:string;target:'local'|'drive'}|null>(null);const [disconnect,setDisconnect]=useState(false);
  const active=useRef(true);const operation=useRef<AbortController|null>(null);const locked=useRef(false);
  const refresh=useCallback(async(signal?:AbortSignal)=>{const files=await backupStore.list(ownerId);if(!active.current)return;setLocal(files);const saved=await apiRequest<typeof status>('/backups/drive',getToken,{signal});if(!active.current)return;setStatus(saved);if(saved.connected){const cloud=await apiRequest<{files:typeof drive}>('/backups/drive/files',getToken,{signal});if(active.current)setDrive(cloud.files);}else setDrive([]);},[ownerId,getToken]);
  useEffect(()=>{active.current=true;const abort=new AbortController();void Promise.resolve().then(()=>refresh(abort.signal)).catch(()=>{if(active.current)setNotice('The archive could not be loaded. Retry when you are connected.');});const subscription=AppState.addEventListener('change',state=>{if(state!=='active'){operation.current?.abort();setArchive(null);setVoiceArchive(null);setKey('');setPrepared(null);setUnlock(null);}else {void refresh().catch(()=>{});}});return()=>{active.current=false;abort.abort();operation.current?.abort();subscription.remove();};},[refresh]);
  // A restored copy remains visible only while its current friendship is open.
  const archiveOpen=Boolean(archive);
  useEffect(()=>{if(!archiveOpen)return;const abort=new AbortController();const check=async()=>{try{const m=await apiRequest<BackupManifest>('/backups/manifest',getToken,{signal:abort.signal});if(!abort.signal.aborted)setArchive(a=>a?{...a,conversations:a.conversations.filter(c=>m.conversations.some(p=>p.peerId===c.peerId))}:null);}catch{if(!abort.signal.aborted)setArchive(null);}};const timer=setInterval(()=>void check(),10000);return()=>{abort.abort();clearInterval(timer);};},[archiveOpen,getToken]);
  async function run(work:(signal:AbortSignal)=>Promise<void>) {if(locked.current)return;locked.current=true;setBusy(true);setNotice('');const abort=new AbortController();operation.current=abort;try{assertAccountOpen(ownerId);await work(abort.signal);}catch(error){if(active.current&&!abort.signal.aborted)setNotice(error instanceof ApiError&&error.code==='DRIVE_UNCONFIGURED'?'Google Drive connection is not available in this build yet.':error instanceof ApiError&&error.code==='DRIVE_RECONNECT'?'Reconnect Google Drive to continue.':'The archive could not finish this step. Check your connection, available storage, and recovery key, then retry.');}finally{locked.current=false;if(active.current)setBusy(false);}}
  async function create(target:'local'|'drive',signal:AbortSignal) {const value=await collectArchive(getToken,signal);const result=await encryptArchive(value);assertAccountOpen(ownerId);if(!signal.aborted&&active.current)setPrepared({...result,target});}
  function connect() {if(locked.current)return;const window=prepareDriveWindow();void run(async signal=>{try{const link=await apiRequest<{id:string;authorizationUrl:string}>('/backups/drive/connect',getToken,{method:'POST',signal});if(signal.aborted)return;await window.open(link.authorizationUrl);if(signal.aborted)return;for(let i=0;i<120;i++){await new Promise<void>(resolve=>{const timer=setTimeout(done,3000);function done(){clearTimeout(timer);signal.removeEventListener('abort',done);resolve();}signal.addEventListener('abort',done,{once:true});});if(signal.aborted)return;const result=await apiRequest<{status:string}>('/backups/drive/links/'+link.id,getToken,{signal});if(result.status==='CONNECTED'){window.close();await refresh(signal);setNotice('Google Drive is connected. Choose when to create a backup.');return;}if(result.status!=='PENDING')throw Error();}throw Error();}catch(error){window.close();throw error;}});}
  return <View style={{gap:24}}>
    <StoryHeading eyebrow="THE ROYAL ARCHIVE" title="A keepsake for your conversations." subtitle="Encrypted copies, kept by you. Your recovery key opens them." />
    <View style={panel}><WaxSeal color="#68516F" /><Text style={s.dialogTitle}>The private vault</Text><Text style={s.body}>Back up delivered text from currently open friendships. This chat backup excludes unsent messages and letters. Use Voice keepsakes below for your own local recordings. Backups are manual, with room for 10 copies in each location and 10,000 messages per copy.</Text><Text style={s.body}>Save each recovery key separately. Lantern Post and Google Drive cannot recover a lost key. Opening a backup never sends its messages again.</Text>
      <StoryButton label="Create a local backup" disabled={busy} onPress={()=>{void run(signal=>create('local',signal));}} /><StoryButton label="Open a backup file" secondary disabled={busy} onPress={()=>{void run(async()=>{const e=await importBackup();if(active.current&&e){setKey('');setUnlock(e);}});}} />
    </View>
    <View style={[panel,{backgroundColor:'#E5EBDF'}]}><Text style={s.dialogTitle}>Beyond the clouds · Google Drive</Text><Text style={s.body}>{status.connected?'Connected. Only Lantern Post’s private backup folder is accessible. Your recovery keys are never uploaded.':status.configured?'Connect your Google account to keep encrypted copies in Drive.':'Google Drive setup is still needed for this build. Local backups are available now.'}</Text>
      {status.connected?<><StoryButton label="Back up to Google Drive" disabled={busy} onPress={()=>{void run(signal=>create('drive',signal));}} /><StoryButton label="Disconnect Google Drive" secondary disabled={busy} onPress={()=>setDisconnect(true)} /></>:<StoryButton label="Connect Google Drive" disabled={busy||!status.configured} onPress={connect} />}
    </View>
    <VoiceBackupPicker ownerId={ownerId} busy={busy} driveConnected={status.connected} onBackup={(selected,caption,target)=>{void run(async signal=>{const result=await prepareVoiceBackup(ownerId,selected,caption);if(!signal.aborted&&active.current)setPrepared({...result,target});});}} />
    {(['local','drive'] as const).map(target=><View key={target} style={panel}><Text style={s.dialogTitle}>{target==='local'?'Kept on this device':'Kept in Google Drive'}</Text>{(target==='local'?local:drive).length===0&&<Text style={s.body}>No keepsakes here yet.</Text>}{(target==='local'?local:drive).map(file=><View key={file.id} style={{gap:10,borderTopWidth:1,borderColor:'#CCB889',paddingTop:15}}><Text style={s.body}>{new Date(file.createdAt).toLocaleString()}</Text><StoryButton label="Open encrypted archive" secondary disabled={busy} onPress={()=>{void run(async signal=>{const e=target==='local'?await backupStore.read(ownerId,file.id):await apiRequest<EncryptedBackup>('/backups/drive/files/'+file.id,getToken,{signal});if(!signal.aborted&&active.current){setKey('');setUnlock(e);}});}} /><StoryButton label="Save backup file" secondary disabled={busy} onPress={()=>{void run(async signal=>{const e=target==='local'?await backupStore.read(ownerId,file.id):await apiRequest<EncryptedBackup>('/backups/drive/files/'+file.id,getToken,{signal});if(!signal.aborted)await exportBackup(e);});}} /><StoryButton label="Remove backup" secondary disabled={busy} onPress={()=>setRemove({id:file.id,target})} /></View>)}</View>)}
    <StoryButton label="Refresh archive" secondary disabled={busy} onPress={()=>{void run(refresh);}} />{busy&&<StoryButton label="Cancel this step" secondary onPress={()=>operation.current?.abort()} />}{Boolean(notice)&&<Text accessibilityLiveRegion="polite" style={s.body}>{notice}</Text>}
    {prepared&&<StoryDialog title="Keep your golden key." onClose={()=>{if(!busy)setPrepared(null);}}><Text style={s.body}>Save this key in your password manager or another safe place, separately from the backup. It will be shown only here.</Text><Text selectable style={[s.body,{fontFamily:'monospace'}]}>{prepared.recoveryKey}</Text>{Boolean(notice)&&<Text accessibilityLiveRegion="polite" style={s.body}>{notice}</Text>}<StoryButton label="I saved my key · save backup" disabled={busy} onPress={()=>{void run(async signal=>{const value=prepared;assertAccountOpen(ownerId);if(value.source&&draftStorage.read(value.source.key)!==value.source.revision)throw Error('This recording changed; prepare a new backup.');if(value.target==='local')await backupStore.save(ownerId,randomUUID(),value.envelope);else await apiRequest('/backups/drive/files',getToken,{method:'POST',body:value.envelope,signal});if(!signal.aborted&&active.current){setPrepared(null);await refresh(signal);setNotice('Your encrypted backup is saved.');}});}} /></StoryDialog>}
    {unlock&&<StoryDialog title="Open your keepsake." onClose={()=>{if(!busy){setUnlock(null);setKey('');}}}><Text style={s.body}>Enter this backup’s recovery key. You must be signed in to its original account; closed friendships stay hidden.</Text><TextInput accessibilityLabel="Backup recovery key" value={key} onChangeText={setKey} autoCapitalize="none" autoCorrect={false} secureTextEntry style={[s.body,{borderWidth:1,borderColor:'#B99A61',padding:12}]} />{Boolean(notice)&&<Text accessibilityLiveRegion="polite" style={s.body}>{notice}</Text>}<StoryButton label="Open archive" disabled={busy||!key.trim()} onPress={()=>{void run(async signal=>{if(unlock.format==='lantern-voice-backup'){const voice=await openVoiceBackup(unlock,key,ownerId);if(!signal.aborted&&active.current){setVoiceArchive(voice);setUnlock(null);setKey('');}return;}const m=await apiRequest<BackupManifest>('/backups/manifest',getToken,{signal});const a=await decryptArchive(unlock,key,m.ownerKey);const fresh=await apiRequest<BackupManifest>('/backups/manifest',getToken,{signal});assertAccountOpen(ownerId);if(!signal.aborted&&active.current){setArchive({...a,conversations:a.conversations.filter(c=>fresh.conversations.some(p=>p.peerId===c.peerId))});setThread(0);setShown(50);setUnlock(null);setKey('');}});}} /></StoryDialog>}
    {voiceArchive&&<VoiceBackupReader ownerId={ownerId} archive={voiceArchive} onClose={()=>setVoiceArchive(null)} />}
    {archive&&<StoryDialog title="A conversation remembered." onClose={()=>setArchive(null)}><Text style={s.body}>Read-only backup from {new Date(archive.createdAt).toLocaleString()}. Nothing here is sent or added to live chat.</Text>{archive.conversations.map((c,index)=><StoryButton key={c.peerId} secondary label={c.username} onPress={()=>{setThread(index);setShown(50);}} />)}{!archive.conversations.length&&<Text style={s.body}>No currently open friendships are available in this backup.</Text>}{archive.conversations[thread]?.messages.slice(-shown).map(m=><View key={m.sequence} style={{padding:16,borderWidth:1,borderColor:'#C7B27F',backgroundColor:m.side==='mine'?'#E5EBDF':'#F7EDDA',borderRadius:14}}><Text style={s.eyebrow}>{m.side==='mine'?'You':'Your friend'} · {new Date(m.createdAt).toLocaleString()}</Text><Text selectable style={s.body}>{m.text}</Text></View>)}{(archive.conversations[thread]?.messages.length??0)>shown&&<StoryButton label="Read earlier pages" secondary onPress={()=>setShown(n=>n+50)} />}</StoryDialog>}
    {remove&&<StoryDialog title="Remove this backup?" onClose={()=>{if(!busy)setRemove(null);}}><Text style={s.body}>This removes only this encrypted copy. Your live conversations remain.</Text><StoryButton label="Remove this copy" disabled={busy} onPress={()=>{void run(async signal=>{if(remove.target==='local')await backupStore.remove(ownerId,remove.id);else await apiRequest('/backups/drive/files/'+remove.id+'/remove',getToken,{method:'POST',signal});setRemove(null);await refresh(signal);});}} /></StoryDialog>}
    {disconnect&&<StoryDialog title="Disconnect Google Drive?" onClose={()=>{if(!busy)setDisconnect(false);}}><Text style={s.body}>Existing backups stay in Drive. Remove them here first if you no longer want them. Disconnecting revokes Lantern Post’s access.</Text><StoryButton label="Disconnect" disabled={busy} onPress={()=>{void run(async signal=>{await apiRequest('/backups/drive/disconnect',getToken,{method:'POST',signal});setDisconnect(false);await refresh(signal);});}} /></StoryDialog>}
  </View>;
}
